### ISSUE TITLE
php2html PHP version issue

### ISSUE THREAD

**Issue by ghost** [bezoerb/php2html#1]
My computer is using PHP 5.5.30 of MAC OSX Elcapitan 10.11.3. 
The error is as follows: 

stream.js:94 
thrower; / Unhandled stream error in pipe. 
Error: 500 – php-cgj exited with code – 1 

I really appreciate some help to solve this problem.

**Comment by bezoerb** [comment]
@adevKi sorry for responding so late. Could you provide some insights about this issue? 
I won't be able to reproduce & fix the error with the information above.
