### ISSUE TITLE
Problems to generate a html from a php-file which include the include() function

### ISSUE THREAD

**Issue by aboutsam** [bezoerb/php2html#2]
hello, i have problems to generate a php which has a include('path');.. is there a way to generate the file and he find the correct location of the files? it is necessary because of my order structure..

**Comment by bezoerb** [comment]
@aboutsam sorry for the late response. There should be no problem in locating the files if you specify an absolute path like in the test (See https://github.com/bezoerb/php2html/blob/master/test/fixtures/index.php)

Can you give some more insights if this doesn't help you?
