### ISSUE TITLE
HTML cannot be generated

### ISSUE THREAD

**Issue by jensgro** [bezoerb/php2html#3]
Although PHP5.6 is installed, I get errors while generating a file directly or via grunt. 

Generating with Grunt the error is about a missing doctype - which is in reality on the first line. Even switching the htmlhint-option for doctype to "false" doesn't change anything.

The error in the console of the main tool reads: "Error: "php-cgi" not found. See https://git.io/vg20U"

But PHP5.6 does exist. I followed the way of the documentation and all steps were deprecated. But in the end an installed PHP5.6 was found. 

Last year everything worked fine. But now everything has crashed.

Do you have an idea for why the error occurs?

**Comment by bezoerb** [comment]
What happens when you call `php-cgi -v` on the command-line?

**Comment by jensgro** [comment]
command not found: php-cgi

On the other hand, brew told me that I have php@5.6 installed, besides other versions.

**Comment by bezoerb** [comment]
Could you check if brew put it somewhere like: /usr/local/Cellar/php56/5.6.33_9/bin/php-cgi (location on my machine)

Then you might only have to link it 
```bash
ln -s /usr/local/Cellar/php56/5.6.33_9/bin/php-cgi /usr/local/bin/php-cgi 
```

**Comment by jensgro** [comment]
I updated php56 with homebrew with the option --with-cgi and ran the grunt-task again. The error-message is: 
Processing site/dev/a11y-screenreader.php...ERROR
>> Resulting HTML is empty

**Comment by jensgro** [comment]
did test it:
ln -s /usr/local/Cellar/php@5.6/5.6.30_6/bin/php-cgi /usr/local/bin/php-cgi

Didn't work either. Very strange.

**Comment by bezoerb** [comment]
Something in your php script might cause an error.
Looks like the error reporting should be optimized :D

Can you try php2html on the command-line?
```bash
npm i -g php2html 
DEBUG=php2html:* php2html site/dev/a11y-screenreader.php
```

**Comment by jensgro** [comment]
` Error: 204 - No Content
`
But I can see content. I see the page.

For the time being I have transformed the PHP with PHP-intern cli-function. Maybe this does the whole trick?
