### ISSUE TITLE
Using php-cgi as a local binary file

### ISSUE THREAD

**Issue by stuartjnelson** [bezoerb/php2html#4]
Hey @bezoerb,

This package is RAD! Thanks for sharing it. I am trying to deploy a site with [netlify](netlify.com) where the are running `Ubuntu Linux v 14.04 LTS using x86_64` and I cannot `apt get` PHP-CGI which is resulting in my build failing. [There docs](https://www.netlify.com/blog/2016/10/18/how-our-build-bots-build-sites/#a-tale-of-several-versions) suggests having the binary file locally. I can't get this to work, any ideas? I'm writing a blog post about how to do this using your plugin so your help would be much appreciated so I can finish it!

Thanks again for sharing this repo.

**Comment by bezoerb** [comment]
hey @stuartjnelson,

if you don't need the router functionality you can try using the PHP-intern cli-function directly like this?
```bash
php myfile.php > myfile.html
```

**Comment by stuartjnelson** [comment]
Thanks for the super fast reply! Is it possible to do that same command on a directory?

**Comment by bezoerb** [comment]
I don't think so. You'll have to iterate over the files and call the command for each file seperately
